### ISSUE TITLE
Allow macro names starting with lowercase letter

### ISSUE THREAD

**Issue by v0dro** [seattlerb/oedipus_lex#11]
Currently, macros can begin only with an upper case letter since the macro variables created in the `*.lex.rb` file are constants defined at the top of the class.

Maybe change this behavior and make them class variables instead so that there are no constraints when it comes to naming macros?

**Comment by zenspider** [comment]
This isn't a priority to me. If you would like to submit a patch it will be welcome.

**Comment by zenspider** [comment]
Seems like it isn't much of a priority at all. Closing.
