### ISSUE TITLE
Getting token line and column number

### ISSUE THREAD

**Issue by v0dro** [seattlerb/oedipus_lex#12]
Is there a way to get the line number, file name and column number of a token matched by oedipus lex?

I'd like to avoid explicitly building this functionality into my lexer, if possible. It would be great if this information could be retrieved without increased bloat.

**Comment by zenspider** [comment]
Yup!

https://github.com/seattlerb/oedipus_lex/blob/master/lib/oedipus_lex.rb#L276-L278

https://github.com/seattlerb/oedipus_lex/blob/master/lib/oedipus_lex.rb#L295-L303

**Comment by v0dro** [comment]
Thank you!

Also one more question:
How do you overcome the limitation that it will match the first regex rule that it comes across? For example, I want to tokenize this file:
```
def structure(a, i32 b, i32 c)
  struct node do
    i32 a
  end
end
```
Now in the above case, I want to identify the `i32` as `:kDTYPE`, the `a`, `b` and `c` as `:tIDENTIFIER` and the `structure` as `:tIDENTIFIER`, and `struct` as `:kSTRUCT`.

However, if I place the regex for `structure` above the regex for `struct`, the token gets identified as `:tIDENTIFIER` and not `:kSTRUCT`.

Here's the lexer file that I'm using:
```
/#{IDENTIFIER}/         { [:tIDENTIFIER, text] }
/#{LPAREN}/             { [:tLPAREN, text] }
/#{RPAREN}/             { [:tRPAREN, text] }
/#{LSQUARE}/            { [:tLSQUARE, text] }
/#{RSQUARE}/            { [:tRSQUARE, text] }
/#{COMMA}/              { [:tCOMMA, text] }
/#{SCOLON}/             { [:tSCOLON, text] }
/#{NL}/                 { [:tNL, text] }
/#{QMARK}/              { [:tQMARK, text]}
/#{DOT}/                { [:tDOT, text]    }

/#{STRUCT}/ { [:kSTRUCT, text] }
/#{UNION}/  { [:kUNION, text]  }
/#{ALIAS}/  { [:kALIAS, text]  }
```

Is there any way a 'longest match first' can be implemented?

**Comment by zenspider** [comment]
Lexing is about values, not semantics. You want to _parse_ semantics, not lex them. Lexing is relatively stupid. All of those with the possible exception of `i32` are some sort of identifier.

See https://github.com/seattlerb/ruby_parser/blob/master/lib/ruby_lexer.rex for a truly horrible lexer example, but notice the bottom.

**Comment by v0dro** [comment]
Ah. Thank you for your help!
