### ISSUE TITLE
column computation speed up

### ISSUE THREAD

**Issue by vdbijl** [seattlerb/oedipus_lex#13]
We noticed that with bigger files the computation of column position gets slow. We suggest the following update. We tried this update on our code and it works. If you agree with the solution we are of course willing to submit it as a pull request.

We keep track of the last newline position in a similar way as the line number. We update it when we see a newline.

We changed the column method
```
def column
    # correct for of by one unless it's the first line                           
    correction = self.lineno == 1 ? 0 : 1                                        
    idx = self.last_newline_pos + correction 
    old_pos - idx
end
```

And in the next_token method
```
...
if ss.peek(1) == "\n"                                                      
  self.lineno += 1                                                         
  self.last_newline_pos = ss.pos                                           
end
```

Thanks for this nice piece of code, we enjoy it!

**Comment by zenspider** [comment]
Thanks! Wanna send in a PR? (no pressure)

**Comment by vdbijl** [comment]
@zenspider, no pressure, gentle reminder that if you have a moment it would be great to receive feedback.

**Comment by zenspider** [comment]
Poking. Thank you for the PR and the nudge.

Curious, how big is a "big file"?

**Comment by zenspider** [comment]
Done! https://www.zenspider.com/releases/2020/06/oedipus_lex-version-2-5-2-has-been-released.html

Thank you!
