### ISSUE TITLE
Allow arbitrary spaces before keywords

### ISSUE THREAD

**Issue by v0dro** [seattlerb/oedipus_lex#9]
Currently the lexer places a restriction that the keywords (like `rule`) must have ZERO spaces before the keyword.

This restriction should be relaxed and an arbitrary number of spaces should be allowed before keywords so that users can indent their code however they want.

**Comment by zenspider** [comment]
This isn't a priority to me. If you would like to submit a patch it will be welcome.

**Comment by zenspider** [comment]
Seems like it isn't much of a priority at all. Closing.
